### ISSUE TITLE
Can we use this in an iOS project?

### ISSUE THREAD

**Issue by xMonty** [RxSwiftCommunity/RxFileMonitor#5]
Can we use this in an iOS project?

**Comment by DivineDominion** [comment]
From what I find on the web, FSEvent is only available on macOS. `NSFileCoordinator` or a lower-lever `kqueue` might work.

**Comment by DivineDominion** [comment]
@xMonty Did you have any success porting this or implementing another mechanism?

**Comment by DivineDominion** [comment]
So probably not :)  Closing this for now.
