### ISSUE TITLE
Suggestion: [weak self]

### ISSUE THREAD

**Issue by hk05** [RxSwiftCommunity/RxFileMonitor#6]
Might you need to access class variables (self.myvar): add [weak self].

```
FolderContentMonitor(url: folderUrl)
    .asObservable()
    .subscribe(onNext: { [weak self] event in
        guard let self = self else { return }
        print("Folder with \(self.myvar) contents changed in directory \(event.url) (\(event.change))")
    })
    .addDisposableTo(disposeBag)
```

Note the added [weak self] before the event.

Not doing so might cause a retain cycle, making it impossible to deinit your class. The Foldermonitor would then (unexpectedly) keep running in the background. This could lead to memory leaks.

**Comment by DivineDominion** [comment]
I changed how `FolderContentMonitor` creates its observable: the subscription does not retain the monitor now. Still, `[weak self]` in client code (see your example) is a good idea for every Rx use case :)

**Comment by hk05** [comment]
Hi Christian,

Thank you for your quick follow up on the issue I (HK05) raised on RxFileMonitor :-)

I am not fully sure if I did something wrong, because I now get another error:
- ran carthage update (to RxFileMonitor 1.3.4)

On code 
        _ = FolderContentMonitor(url: url!)
            .folderContentChange
            .observeOn(MainScheduler.instance)
...


I now get Value of type 'FolderContentMonitor' has no member 'folderContentChange'

Btw, I took a look at your examples in the readme. Only the first example was modified, so that might have caused a misinterpretation on my side on how to use folderContentChange(?)

Again: thanks for your quick update :-)

Hans

**Comment by DivineDominion** [comment]
You're absolutely right, I did a haphazard job updating the README. Now it should reflect the current state of the library properly.

You will be using it as:

```swift
FolderContentMonitor(url: url!).rx.folderContentChange
```

(note the `.rx`)

Please also note that the memory management model did change and you will need to keep the `FolderContentMonitor` alive yourself.

**Comment by hk05** [comment]
Hi Christian,

Thanks providing this pointer, it works :-D

It is wonderful to notice that people like you reply so quickly and come up with a fix. I really appreciate that very much Christian! 

Thanks again and greetings from your neighbour in The Netherlands :-)

Have a nice evening,

Hans

**Comment by DivineDominion** [comment]
You're welcome! 🙌 :)

**Comment by hk05** [comment]
Hi Christian,

Sorry to interrupt you by direct mail (I though I’d better not create an issue at github as this might relate to something silly).

I updated and successfully rebuild your RxFileMonitor. However, it seems to not trigger events. I copied the example from the README:

    @IBAction func something2(_ sender: Any) {
        let folderUrl = URL(fileURLWithPath: "/Users/myhomediretcory/")
        let monitor = FolderContentMonitor(url: folderUrl)
        
        monitor.rx.folderContentChange
            .subscribe(onNext: { event in
                print("Folder contents changed at \(event.url) (\(event.change))")
            })
            .disposed(by: disposeBag)
    }

When I run this function, I’d expect to receive a console message when something in that directory changes. However, nothing happens.

I have been trying to figure out what I could be doing wrong myself, but could not figure it out. I ended with a literate copy of the example (except the dir name of course, see copied code above). 

Could it be that things are not yet working as expected in xcode 10.2/Swift 5, or did I look over something?

Thanks and have a nice day!

Hans

**Comment by DivineDominion** [comment]
That's weird!

Have you tried to run the example app? Does that work for you? If you add .debug() to the folderContentChange observable stream, do you see events and subscription debug message in the console? (Maybe even a dispose message?)

-- Christian

**Comment by hk05** [comment]
Hi Christian,

Thanks for contacting. 

I tried, but could not get the example app to run (yet, still fiddling without much result).

I commented out all references in my own code, because it was not working. RxFileMonitor seemed dead (I could not detect any event anywhere). I have not dug deep into this in my own code, nor did I experiment with inserting debug()’s into the observable stream, as I am still learning RxSwift and did not feel very comfortable debugging it. I did sepend a several hours trying to figure out what could be wrong before contacting you, but I felt stuck. So basically, I did notice that everything compiles fine, no errors or warnings. But at runtime, nothing seems to happen. 

I will try to dig in further tomorrow. But at the same time I have to add that I am not expecting too much findings on my side, as I am quite unsure on how to approach debugging RxFileMonitor.

Does RxFilemonitor work well in your environment? I just upgraded to 10.2/Swift 5, so maybe there is an issue with that(?!)

BR

Hans

**Comment by DivineDominion** [comment]
I have just launched Xcode 10.2 and ran the Example app from the repository. It compiles and runs, I can select a directory, edit files in the directory, and see events in the example app's event log. So it works here so far, on macOS 10.14.

Looking forward to seeing what you find!

-- Christian

**Comment by hk05** [comment]
Hi Christian,

Ok, I re-downloaded and rebuild. Until now I got a runtime crash. Probably my mistake as I have a love-hate relationship with carthage.

I just started again from scratch and got something running now. I see messages passing in a window. I also get a console message though:

objc[61088]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff98a523c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x108478f50). One of the two will be used. Which one is undefined.
2019-04-15 21:55:20.502096+0200 Example[61088:4237458] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}

So, my conclusion is that the events seems to be triggering in the example. That leaves my ??’s as to why the events are not triggering in my app. All I did is insert the “self.monitor.rx.folderContentChange” as instructed in the readme.md. I will look into this a bit further tomorrow, and see if I can do something with inserting debug() statements… 

Thank yo u so far for your help.

BR

Hans

**Comment by hk05** [comment]
Hi Christian,

I just made some modifications in my own code and I think I got it tackled. I seem to have made a mistake in the change to monitor.rx.folderContentChange. That is: it looks like the monitor was deallocated before it started catching the events. That seems to be my own mistake, for which I apologize towards you (I’m terribly sorry for having taken some of your time Christian). 

Tomorrow I will dig in a bit further to assure myself everything is ok, but now I need a bit of sleep to get my head straight again ;-)

If everything is working ok again I will snd you a brief confirmation.

Thank you so much for your assistance and patience!

Hans

**Comment by DivineDominion** [comment]
Cool. Crossing my fingers that it will work :)

-- Christian

**Comment by hk05** [comment]
Good morning Christian,

Good news: everything is working ok!


The new syntax caused a mistake on my side. Originally my (working) code looked like this:

        _ = FolderContentMonitor(url: url!, latency: 0.9)
            .asObservable()

At the 10.2 update on RxFileMonitor I assumed I could just change into:

        _ = FolderContentMonitor(url: url, latency: 0.8)
            .rx.folderContentChange
...

This does compile correctly, but it does not trigger the events.

Somehow I managed to overlook some other difference in your example code. When I explicitly assign the FolderContentMonitor to a class variable, everything works well again:

        monitor = FolderContentMonitor(url: url, latency: 0.8)

        monitor
            .rx.folderContentChange
...


I am quite surprised that I did not notice all subtle changes in the code example you gave. I guess that was on my blind spot. I did not look closely enough. For which I apologise, because I should have figured this out without bothering you. I owe you one. 

I cannot thank you enough for your kindness and patience.

Wishing you a wonderful day!


Hans

**Comment by DivineDominion** [comment]
Yeah, sorry for the memory management change in recent updates! Maybe I should've made this a 2.x release to emphasize the change.

Glad it works now :)

-- Christian

**Comment by hk05** [comment]
Well, I should have paid closer attention myself. I should improve my reading skills ;-)

Sorry for the inconvenience, but a great thank you for everything!

And the end result is good: I too am certainly very glad it works now as well.

:-)

Hans
