### ISSUE TITLE
Error in xcode 10.2

### ISSUE THREAD

**Issue by hk05** [RxSwiftCommunity/RxFileMonitor#7]
I am updating xcode to 10.2 / swift 5. All libraries, including RxSwift compile well now, except RxFileMonitor. RxFileMonitor is giving me an error "Value of type 'FolderContentMonitor' has no member 'asObservable'". 

Does anyone have an idea how to fix this?

**Comment by DivineDominion** [comment]
Whoops, forgot to update the README! When I fixed a retain cycle, I renamed `asObservable()` to `folderContentChange` to better reflect the changes. That should work now.
