### ISSUE TITLE
Carthage install breaks on 5.1

### ISSUE THREAD

**Issue by matthewcoxx** [RxSwiftCommunity/RxFileMonitor#9]
Carthage install breaks on Swift 5.1 with the following:

"Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)."

**Comment by DivineDominion** [comment]
It should rebuild from source in that case 🤔 Updated the project to be ready for Xcode 11/Swift 5.1 now, though! Thanks for bringing this up!
